# Generated by Django 2.1.1 on 2018-09-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasGecal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linhadepesquisa',
            old_name='data',
            new_name='data_conclusao',
        ),
        migrations.AddField(
            model_name='linhadepesquisa',
            name='comentarios_adicionais',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=70),
        ),
    ]
