# Generated by Django 2.1.1 on 2018-09-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasGecal', '0003_auto_20180921_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsista',
            name='email',
            field=models.EmailField(default='email_exemplo@default.com', help_text='email do bolsista', max_length=254),
        ),
        migrations.AddField(
            model_name='linhadepesquisa',
            name='tipo_de_projeto',
            field=models.CharField(choices=[('p', 'pesquisa'), ('e', 'extensao')], default='p', help_text='definir tipo de projeto > pesquisa / extensão', max_length=1),
        ),
    ]
