# Generated by Django 2.1.1 on 2018-09-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasGecal', '0004_auto_20180929_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linhadepesquisa',
            old_name='estagio_da_pesquisa',
            new_name='estagio_do_projeto',
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='email',
            field=models.EmailField(default='email_exemplo@default.comp', help_text='email do bolsista', max_length=254),
        ),
    ]
