# Generated by Django 2.1.1 on 2018-09-30 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasGecal', '0005_auto_20180929_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='formulario_denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_denunciante', models.TextField(blank=True)),
                ('email_denunciante', models.EmailField(blank=True, max_length=254)),
                ('telefone_denunciante', models.TextField(blank=True)),
                ('tipo_de_experiencia', models.CharField(blank=True, choices=[('v', 'vivenciou'), ('p', 'presenciou')], default='v', help_text='Foi testemunha ou vítima?', max_length=1)),
                ('violencia_fisica', models.BooleanField(default=False)),
                ('violencia_psicologica', models.BooleanField(default=False)),
                ('assedio_sexual', models.BooleanField(default=False)),
                ('assedio_moral', models.BooleanField(default=False)),
                ('violencia_patrimonial', models.BooleanField(default=False)),
                ('homofobia', models.BooleanField(default=False)),
                ('lesbofobia', models.BooleanField(default=False)),
                ('transfobia', models.BooleanField(default=False)),
                ('ameaca_verbal', models.BooleanField(default=False)),
                ('outros', models.BooleanField(default=False)),
                ('txt_outros', models.TextField(blank=True)),
                ('txt_relato', models.TextField()),
                ('data_relato', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='universidade',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
