# Generated by Django 2.1.1 on 2018-10-01 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasGecal', '0007_formulario_denuncia_estupro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario_denuncia',
            name='data_relato',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='formulario_denuncia',
            name='tipo_de_experiencia',
            field=models.CharField(choices=[('v', 'vivenciou'), ('p', 'presenciou')], default='v', help_text='Foi testemunha ou vítima?', max_length=1),
        ),
        migrations.AlterField(
            model_name='linhadepesquisa',
            name='data_conclusao',
            field=models.DateField(blank=True, default=datetime.datetime.today, help_text='data de conclusão ou previsão de conclusão'),
        ),
        migrations.AlterField(
            model_name='linhadepesquisa',
            name='data_inicio',
            field=models.DateField(blank=True, default=datetime.datetime.today, help_text='inicio do projeto'),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='dtNascimento',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
    ]
