# Generated by Django 2.1.1 on 2018-10-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginasGecal', '0008_auto_20181001_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisador',
            name='cpf',
        ),
    ]
